version: '3.7'
networks:
  net-aspen:
services:

  backend:
    image: ${BACKEND_IMAGE_TAG:-aspendiscoveryofficial/aspen}
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - net-aspen
    tty: true
    volumes:
      - ${ASPEN_REPO}:/mnt
    depends_on:
      - db

  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ${ASPEN_REPO}/mariadb_data:/var/lib/mysql
    networks:
      - net-aspen

  solr:
    image: ${SOLR_IMAGE_TAG:-aspendiscoveryofficial/solr}
    env_file:
      - .env
    environment:
      - SOLR_PORT=${SOLR_PORT}
      - SOLR_HOST=${SOLR_HOST}
    ports:
      - "${SOLR_PORT}:${SOLR_PORT}"
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ${ASPEN_REPO}/solr_data:/var/solr
    networks:
      - net-aspen
    depends_on:
      - backend

  tunnel:
    image: ${TUNNEL_IMAGE_TAG:-aspendiscoveryofficial/tunnel}
    env_file:
      - .env
    deploy:
      endpoint_mode: dnsrr
    networks:
      - net-aspen
    depends_on:
      - backend
