version: '3.7'
networks:
  net-aspen:
services:

  backend:
    image: aspen-discovery/aspen:${COMPOSE_ImageVersion}
    build:
      context: ~/${ASPEN_Instance}/aspen-discovery/docker
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - net-aspen
    tty: true
    volumes:
      - ~/${ASPEN_Instance}:/mnt

  db:
    image: mariadb:10.3
    environment:
      - MARIADB_ROOT_PASSWORD=${COMPOSE_RootPwd}
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ~/${ASPEN_Instance}/mariadb_data:/var/lib/mysql
    networks:
      - net-aspen

  solr:
    image: aspen-discovery/solr:${COMPOSE_ImageVersion}
    build:
      context: ~/${ASPEN_Instance}/aspen-discovery/docker/solr
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8983:8983"
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ~/${ASPEN_Instance}:/mnt
      - ~/${ASPEN_Instance}/solr_data:/var/solr
    networks:
      - net-aspen
    depends_on:
      - backend
      
  tunnel:
    image: aspen-discovery/aspen:${COMPOSE_ImageVersion}
    env_file:
      - .env
    environment:
      - COMPOSE_Cron=off
      - COMPOSE_Apache=off
      - COMPOSE_Solr=off
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - ~/${ASPEN_Instance}:/mnt
    networks:
      - net-aspen
    entrypoint: ["/root/.ssh/tunnel.sh"]
